services:

  caddy:

    image: caddy:2

    container_name: caddy

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/data/caddy/data:/data
      - /opt/data/caddy/config:/config

    networks:
      - proxy

networks:

  proxy:
    external: true
